export const types = {
    START_FETCHING:    "START_FETCHING",
    STOP_FETCHING:     "STOP_FETCHING",
    EMIT__ERROR:       "EMIT__ERROR",
    SET_ONLINE_STATE:  "SET_ONLINE_STATE",
    SET_OFFLINE_STATE: "SET_OFFLINE_STATE",
};
